# Search

In [1]:
import numpy as np

In [7]:
var = np.array([1,2,3,4,2,5,2,5,6,7])


x = np.where(var == 2)

print(x) 

(array([1, 4, 6], dtype=int64),)


In [8]:
var = np.array([1,2,3,4,2,5,2,5,6,7])


x = np.where(var/2 == 0)

print(x) 

(array([], dtype=int64),)


In [10]:
var = np.array([1,2,3,4,5,6,7])


x1 = np.where(var%2 == 0)

print(x) 

(array([0, 1, 3, 4, 6, 8], dtype=int64),)


# Searchsorted

In [14]:
var1 = np.array([1,2,3,4,2,5,2,5,6,7])


x1 = np.searchsorted(var1 , 5)

print(x1) 

5


In [22]:
var1 = np.array([1,2,3,4,9,10])


x1 = np.searchsorted(var1 , [5,6,7],side="right")

print(x1) 

[4 4 4]


# sort

In [23]:
var2 = np.array([4,2,3,1,12,5,22,52,6,7])

print(np.sort(var2))

[ 1  2  3  4  5  6  7 12 22 52]


In [25]:
var3 = (["a","d","e","r","y",])

print(np.sort(var3))

['a' 'd' 'e' 'r' 'y']


In [26]:
var2 = np.array([[4,2,3],[1,12,5],[22,52,6]])

print(np.sort(var2))

[[ 2  3  4]
 [ 1  5 12]
 [ 6 22 52]]


# filter

In [27]:
var4 = np.array(["a","d","e","r","y",])
f = [True,False,True,False,True]
new = var4[f]
print(new)
print(type(new))

['a' 'e' 'y']
<class 'numpy.ndarray'>
