# Shuffle

In [1]:
import numpy as np

In [2]:
var = np.array([1,2,3,4,5])
np.random.shuffle(var)
print(var)

[3 1 2 4 5]


# unique

In [4]:
var2 = np.array([1,2,3,4,2,5,2,6,2,7])
x = np.unique(var2)
print(x)

[1 2 3 4 5 6 7]


In [5]:
var2 = np.array([1,2,3,4,2,5,2,6,2,7])
x = np.unique(var2,return_index=True)
print(x)

(array([1, 2, 3, 4, 5, 6, 7]), array([0, 1, 2, 3, 5, 7, 9], dtype=int64))


In [6]:
 var2 = np.array([1,2,3,4,2,5,2,6,2,7])
x = np.unique(var2,return_index=True,return_counts=True)
print(x)

(array([1, 2, 3, 4, 5, 6, 7]), array([0, 1, 2, 3, 5, 7, 9], dtype=int64), array([1, 4, 1, 1, 1, 1, 1], dtype=int64))


# Resize

In [10]:
var3 = np.array([1,2,3,4,5,6])
y = np.resize(var3,(2,3))

print(y)

[[1 2 3]
 [4 5 6]]


In [11]:
var3 = np.array([1,2,3,4,5,6])
y = np.resize(var3,(3,2))

print(y)

[[1 2]
 [3 4]
 [5 6]]


# Flatten

In [15]:
var3 = np.array([1,2,3,4,5,6])
y = np.resize(var3,(3,2))
print(y)
print()
print(y.flatten())

[[1 2]
 [3 4]
 [5 6]]

[1 2 3 4 5 6]


In [18]:
var3 = np.array([1,2,3,4,5,6])
y = np.resize(var3,(3,2))
print(y)
print()
print("Flatten :",y.flatten(order="f"))
print("Ravel :",np.ravel(y,order="f"))

[[1 2]
 [3 4]
 [5 6]]

Flatten : [1 3 5 2 4 6]
Ravel : [1 3 5 2 4 6]


In [19]:
var3 = np.array([1,2,3,4,5,6])
y = np.resize(var3,(3,2))
print(y)
print()
print("Flatten :",y.flatten(order="f"))
print("Ravel :",np.ravel(y,order="A"))

[[1 2]
 [3 4]
 [5 6]]

Flatten : [1 3 5 2 4 6]
Ravel : [1 2 3 4 5 6]
