In [3]:
import numpy as np

var1 = np.array([1,2,3])
print(var1.shape)
print()
print(var1)


var2 = np.array([[1],[2],[3]])
print(var2.shape)
print()
print(var2)

print(var1+var2)

(3,)

[1 2 3]
(3, 1)

[[1]
 [2]
 [3]]
[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [6]:
x = np.array([[1],[2]])
print(x.shape)

y = np.array([[1,2,3],[1,2,3]])
print(y.shape)

print(x+y)

(2, 1)
(2, 3)
[[2 3 4]
 [3 4 5]]
