In [1]:
import numpy as np 
var = np.array([1,2,3,4])
print("data type : ",var.dtype)

data type :  int32


In [2]:
var = np.array([1.0,1.2,1.3])
print("data type : ",var.dtype)

data type :  float64


In [3]:
var = np.array(["a","b","s","h"])
print("data type : ",var.dtype)

data type :  <U1


In [4]:
var = np.array(["a","b","s","h",1,2,3,4,5])
print("data type : ",var.dtype)

data type :  <U11


In [5]:
x = np.array([1,2,3,40],dtype = np.int8)
print("data type :",x.dtype)
print(x)

data type : int8
[ 1  2  3 40]


In [6]:
x = np.array([1,2,3,40],dtype = "f")
print("data type :",x.dtype)
print(x)

data type : float32
[ 1.  2.  3. 40.]


In [7]:
x2 = np.array([1,2,3,4])
new = np.float32(x2)
print("data type :",x2.dtype)
print("data type :",new.dtype)

print(x2)
print(new)

data type : int32
data type : float32
[1 2 3 4]
[1. 2. 3. 4.]


In [8]:
x2 = np.array([1,2,3,4])
new = np.float32(x2)
new_one = np.int_(new)
print("data type :",x2.dtype)
print("data type :",new.dtype)
print("data type :",new_one.dtype)

print(x2)
print(new)
print(new_one)

data type : int32
data type : float32
data type : int32
[1 2 3 4]
[1. 2. 3. 4.]
[1 2 3 4]


In [9]:
x3 = np.array([1,2,3,4])
new_1 = x3.astype(float)
print(x3)
print(new_1)

[1 2 3 4]
[1. 2. 3. 4.]
