In [1]:
import numpy as np

In [2]:
var = np.array([9,8,7,6])
print(var[1])
print(var[-3])

8
8


In [3]:
var1 = np.array([[9,8,7,],[4,5,6]])
print(var1)
print(var1.ndim)
print()
print(var1[0,1])

[[9 8 7]
 [4 5 6]]
2

8


In [4]:
var2 = np.array([[[1,2],[6,7]]])

print(var2)
print(var2.ndim)
print()
print(var2[0,1,1])

[[[1 2]
  [6 7]]]
3

7


# Slicing

In [5]:
var3 = np.array([9,8,7,6,5,4,3])
print(var3)
print()
print("2 to 5 : ",var3[1:5])
print(" 2 to End : ",var3[1:])
print("start to 5 : ",var3[1:])
print("stop : ",var3[1:5:2])

[9 8 7 6 5 4 3]

2 to 5 :  [8 7 6 5]
 2 to End :  [8 7 6 5 4 3]
start to 5 :  [8 7 6 5 4 3]
stop :  [8 6]


In [6]:
var3 = np.array([9,8,7,6,5,4,3])
print(var3)
print()
print("2 to 5 : ",var3[1:5])
print(" 2 to End : ",var3[1:])
print("start to 5 : ",var3[1:])
print("stop : ",var3[::2])

[9 8 7 6 5 4 3]

2 to 5 :  [8 7 6 5]
 2 to End :  [8 7 6 5 4 3]
start to 5 :  [8 7 6 5 4 3]
stop :  [9 7 5 3]


In [9]:
var4 = np.array([[1,2,3,4,5],[9,8,7,6,5],[11,12,13,14,15,]])
print(var4)
print()
print("8 to 5 :",var4[1,1:])

[[ 1  2  3  4  5]
 [ 9  8  7  6  5]
 [11 12 13 14 15]]

8 to 5 : [8 7 6 5]


In [10]:
var4 = np.array([[1,2,3,4,5],[9,8,7,6,5],[11,12,13,14,15,]])
print(var4)
print()
print("8 to 5 :",var4[2,1:])

[[ 1  2  3  4  5]
 [ 9  8  7  6  5]
 [11 12 13 14 15]]

8 to 5 : [12 13 14 15]
