# Matrix

In [1]:
import numpy as np 

In [5]:
var = np.matrix([[1,2,3],[1,2,3,]])
print(var)
print(type(var))

[[1 2 3]
 [1 2 3]]
<class 'numpy.matrix'>


In [6]:
var1 = np.array([[1,2,3],[1,2,3]])
print(var1)
print(type(var1))

[[1 2 3]
 [1 2 3]]
<class 'numpy.ndarray'>


# Arithmetic Operation

In [8]:
var = np.matrix([[1,2],[1,2]])
var2 = np.matrix([[1,2],[1,2]])
print(var)
print(type(var))
print(var*var2)

[[1 2]
 [1 2]]
<class 'numpy.matrix'>
[[3 6]
 [3 6]]


In [10]:
var = np.matrix([[1,2],[1,2]])
var2 = np.matrix([[1,2],[1,2]])
print(var)
print(type(var))
print(var*var2)
print(var.dot(var2))

[[1 2]
 [1 2]]
<class 'numpy.matrix'>
[[3 6]
 [3 6]]
[[3 6]
 [3 6]]


# Transpose

In [13]:
var3 = np.matrix([[1,2,3],[4,5,6]])
print(var3)
print()
print(np.transpose(var3))
print(var3.T)

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]


# Swapaxes

In [16]:
var3 = np.matrix([[1,2,3],[4,5,6]])
print(var3)
print()
print(np.transpose(var3))
print(var3.T)
print()
print(np.swapaxes(var3,0,1))

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]

[[1 4]
 [2 5]
 [3 6]]


In [18]:
var4 = np.matrix([[1,2],[3,4]])
print(var4)
print()
print(np.swapaxes(var4,0,1))

[[1 2]
 [3 4]]

[[1 3]
 [2 4]]


# Inverse

In [19]:
var4 = np.matrix([[1,2],[3,4]])
print(var4)
print()

print(np.linalg.inv(var4))

[[1 2]
 [3 4]]

[[-2.   1. ]
 [ 1.5 -0.5]]


# Power

In [23]:
var4 = np.matrix([[1,2],[3,4]])
print(var4)
print()

print(np.linalg.matrix_power(var4,2))
print(np.linalg.matrix_power(var4,0))
print()
print(np.linalg.matrix_power(var4,-2))

[[1 2]
 [3 4]]

[[ 7 10]
 [15 22]]
[[1 0]
 [0 1]]

[[ 5.5  -2.5 ]
 [-3.75  1.75]]


# Determinate

In [25]:
var5 = np.matrix([[1,2],[3,4]])
print(var5)
print()
print(np.linalg.det(var5))

[[1 2]
 [3 4]]

-2.0000000000000004


In [26]:
var5 = np.matrix([[1,2,3],[3,4,3],[1,2,3]])
print(var5)
print()
print(np.linalg.det(var5))

[[1 2 3]
 [3 4 3]
 [1 2 3]]

0.0
