# Rand()

In [1]:
import numpy as np
var = np.random.rand(4)
print(var)

[0.37653063 0.72875788 0.1785958  0.79270516]


In [3]:
var1 = np.random.rand(2,5)
var1

array([[0.6207861 , 0.95656419, 0.0698138 , 0.12296545, 0.2352255 ],
       [0.8535187 , 0.03855467, 0.68401777, 0.78030004, 0.2994555 ]])

# Randn()

In [4]:
var2 = np.random.randn(5)
var2

array([ 0.64609796, -0.3224714 , -0.83131068,  1.02699829, -1.26973051])

# Ranf()

In [5]:
var3 = np.random.ranf(5)
var3

array([0.1540351 , 0.04920618, 0.45156328, 0.11301867, 0.58940589])

# Randint()

In [16]:
var4 = np.random.randint(4,50,10)
var4

array([38, 27,  5, 14, 41, 48, 19,  9, 46,  5])