In [1]:
import numpy as np
ar_zero = np.zeros(4)
ar_zero1 = np.zeros((3,4))
print(ar_zero)
print()
print(ar_zero1)

[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# Ones

In [2]:
ar_one = np.ones(4)
print(ar_one)

[1. 1. 1. 1.]


# Empty

In [4]:
ar_em = np.empty(4)
print(ar_em)

[1. 1. 1. 1.]


# Range

In [6]:
ar_rn = np.arange(4)
print(ar_rn)

[0 1 2 3]


# Diagonal

In [9]:
ar_dia = np.eye(4)
print(ar_dia)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [10]:
ar_dia = np.eye(3,5)
print(ar_dia)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


# Linspace

In [12]:
ar_lin = np.linspace(0,20,num=5)
print(ar_lin)

[ 0.  5. 10. 15. 20.]
